name:                grammar-tool
version:             0.1.0.0
github:              "jthornber/grammar-tool"
license:             GPL3
author:              "Joe Thornber"
maintainer:          "joe.thornber@gmail.com"
copyright:           "2019 RedHat Ltd"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/grammar-tool#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- prettyprinter

library:
  source-dirs: src

executables:
  grammar-tool:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - grammar-tool

tests:
  grammar-tool-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - grammar-tool
